version: '3.8'

services:
  flask1:
    build: .
    environment:
      - MONGO_URI=${MONGO_URI}
    networks:
      - backend

  flask2:
    build: .
    environment:
      - MONGO_URI=${MONGO_URI}
    networks:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask1
      - flask2
    networks:
      - backend

networks:
  backend: